
CREATE TABLE tags (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  code character varying NOT NULL,
  label character varying,
  PRIMARY KEY (id)
);


CREATE TABLE users (
  user_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp without time zone NOT NULL,
  deleted boolean NOT NULL,
  updated_at timestamp without time zone,
  cpf character varying NOT NULL,
  active boolean NOT NULL,
  birth_date date NOT NULL,
  email character varying NOT NULL,
  email_verified boolean NOT NULL,
  firstname character varying NOT NULL,
  lastname character varying NOT NULL,
  password_hash character varying NOT NULL,
  phone character varying,
  user_type character varying NOT NULL,
  PRIMARY KEY (user_id)
);

CREATE TABLE organizations (
  organization_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp without time zone NOT NULL,
  deleted boolean NOT NULL,
  updated_at timestamp without time zone,
  cnpj character varying NOT NULL,
  active boolean NOT NULL,
  city character varying,
  state character varying,
  zip_code character varying,
  description character varying,
  email character varying NOT NULL,
  logo_image_url character varying,
  name character varying NOT NULL,
  password_hash character varying NOT NULL,
  phone character varying,
  verified boolean NOT NULL,
  website character varying,
  PRIMARY KEY (organization_id)
);

CREATE TABLE events (
  event_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp without time zone NOT NULL,
  deleted boolean NOT NULL,
  updated_at timestamp without time zone,
  active boolean NOT NULL,
  city character varying,
  state character varying,
  zip_code character varying,
  completed boolean NOT NULL,
  cover_image_url character varying,
  description character varying,
  end_date timestamp without time zone NOT NULL,
  filled_slots integer NOT NULL,
  points_reward integer NOT NULL,
  start_date timestamp without time zone NOT NULL,
  title character varying NOT NULL,
  volunteer_slots integer NOT NULL,
  organization_id bigint NOT NULL,
  PRIMARY KEY (event_id),
  FOREIGN KEY (organization_id) REFERENCES organizations(organization_id)
);


CREATE TABLE benefits (
  benefit_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp without time zone NOT NULL,
  deleted boolean NOT NULL,
  updated_at timestamp without time zone,
  description character varying,
  title character varying NOT NULL,
  event_id bigint NOT NULL,
  PRIMARY KEY (benefit_id),
  FOREIGN KEY (event_id) REFERENCES events(event_id)
);



CREATE TABLE news (
  news_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp without time zone NOT NULL,
  deleted boolean NOT NULL,
  updated_at timestamp without time zone,
  body character varying NOT NULL,
  image_url character varying NOT NULL,
  publish_date timestamp without time zone NOT NULL,
  title character varying NOT NULL,
  type character varying NOT NULL,
  event_id bigint,
  PRIMARY KEY (news_id),
  FOREIGN KEY (event_id) REFERENCES events(event_id)
);


CREATE TABLE notifications (
  notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  message character varying,
  read boolean NOT NULL,
  sent_at timestamp without time zone NOT NULL,
  type character varying NOT NULL,
  user_id bigint NOT NULL,
  PRIMARY KEY (notification_id),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE profiles (
  profile_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp without time zone NOT NULL,
  deleted boolean NOT NULL,
  updated_at timestamp without time zone,
  city character varying,
  state character varying,
  zip_code character varying,
  bio character varying,
  headline character varying,
  description character varying,
  profession character varying,
  profile_image_url character varying,
  completed_events integer NOT NULL,
  level integer NOT NULL,
  points integer NOT NULL,
  public_profile boolean NOT NULL,
  streak_days integer NOT NULL,
  total_volunteer_hours integer NOT NULL,
  profile_url character varying,
  user_id bigint NOT NULL,
  PRIMARY KEY (profile_id),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);


CREATE TABLE profile_links (
  profile_id bigint NOT NULL,
  link character varying,
  FOREIGN KEY (profile_id) REFERENCES profiles(profile_id)
);

CREATE TABLE profile_skills (
  profile_id bigint NOT NULL,
  skill character varying,
  FOREIGN KEY (profile_id) REFERENCES profiles(profile_id)
);



CREATE TABLE profile_tags (
  profile_id bigint NOT NULL,
  tag_id bigint NOT NULL,
  PRIMARY KEY (profile_id, tag_id),
  FOREIGN KEY (profile_id) REFERENCES profiles(profile_id),
  FOREIGN KEY (tag_id) REFERENCES tags(id)
);


CREATE TABLE certificates (
  certificate_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp without time zone NOT NULL,
  deleted boolean NOT NULL,
  updated_at timestamp without time zone,
  date_certified timestamp without time zone NOT NULL,
  hours integer NOT NULL,
  event_id bigint NOT NULL,
  organization_id bigint NOT NULL,
  owner_id bigint NOT NULL,
  PRIMARY KEY (certificate_id),
  FOREIGN KEY (event_id) REFERENCES events(event_id),
  FOREIGN KEY (organization_id) REFERENCES organizations(organization_id),
  FOREIGN KEY (owner_id) REFERENCES users(user_id)
);

CREATE TABLE comments (
  comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp without time zone NOT NULL,
  deleted boolean NOT NULL,
  updated_at timestamp without time zone,
  content character varying NOT NULL,
  news_id bigint,
  parent_comment_id bigint,
  user_id bigint NOT NULL,
  PRIMARY KEY (comment_id),
  FOREIGN KEY (news_id) REFERENCES news(news_id),
  FOREIGN KEY (parent_comment_id) REFERENCES comments(comment_id),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE event_likes (
  like_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp without time zone NOT NULL,
  deleted boolean NOT NULL,
  updated_at timestamp without time zone,
  event_id bigint NOT NULL,
  user_id bigint NOT NULL,
  PRIMARY KEY (like_id),
  FOREIGN KEY (event_id) REFERENCES events(event_id),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE event_tags (
  event_id bigint NOT NULL,
  tag_id bigint NOT NULL,
  PRIMARY KEY (event_id, tag_id),
  FOREIGN KEY (event_id) REFERENCES events(event_id),
  FOREIGN KEY (tag_id) REFERENCES tags(id)
);

CREATE TABLE event_volunteers (
  event_id bigint NOT NULL,
  user_id bigint NOT NULL,
  PRIMARY KEY (event_id, user_id),
  FOREIGN KEY (event_id) REFERENCES events(event_id),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE news_tags (
  news_id bigint NOT NULL,
  tag_id bigint NOT NULL,
  PRIMARY KEY (news_id, tag_id),
  FOREIGN KEY (news_id) REFERENCES news(news_id),
  FOREIGN KEY (tag_id) REFERENCES tags(id)
);

CREATE TABLE user_organizations (
  organization_id bigint NOT NULL,
  user_id bigint NOT NULL,
  PRIMARY KEY (organization_id, user_id),
  FOREIGN KEY (organization_id) REFERENCES organizations(organization_id),
  FOREIGN KEY (user_id) REFERENCES users(user_id)
);

CREATE TABLE reports (
  report_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at timestamp without time zone NOT NULL,
  deleted boolean NOT NULL,
  updated_at timestamp without time zone,
  admin_notes character varying,
  description character varying NOT NULL,
  status character varying,
  type character varying NOT NULL,
  reported_by bigint NOT NULL,
  reported_event bigint,
  reported_organization bigint,
  reported_user bigint,
  PRIMARY KEY (report_id),
  FOREIGN KEY (reported_by) REFERENCES users(user_id),
  FOREIGN KEY (reported_event) REFERENCES events(event_id),
  FOREIGN KEY (reported_organization) REFERENCES organizations(organization_id),
  FOREIGN KEY (reported_user) REFERENCES users(user_id)
);
